### ISSUE TITLE
Clarification on the formatting of the input file

### ISSUE THREAD

**Issue by ThomasSchnapka** [algebraic-solving/msolve#121]
First of all thanks for open-sourcing your work, it is very appreciated! 💯 

On a regular basis, I have trouble with the formatting of the input file. For example, the following equation system seems just fine for me:
```
a, b, s, lamA, lamB
0
0.4750117565367643 + lamA * 0.05698810324224207 - b * 14.145271207860723 + b*s * 1.0878512413314014 - a * 0.9823487845322446 - a*s * 9.840557894587773,
0.24620471651887643 - lamA * 0.030110441242706842 + b * 0.0 + b*s * 0.0 + a * 0.0 + a*s * 0.0,
0.18477765545456737 - lamA * 1 - b * 0.9823487845322446 - b*s * 9.840557894587773 + a * 14.145271207860723 - a*s * 1.0878512413314014,
0.4750117565367643 + lamB * 0.05698810324224207 - b * 7.824159668166666 + b*s * 1.0878512413314014 - a * 0.9783577693832235 - a*s * 9.840557894587773,
0.24620471651887643 - lamB * 0.030110441242706842 + b * 0.0 + b*s * 0.0 + a * 0.0 + a*s * 0.0,
0.18477765545456737 - lamB * 1 - b * 0.9783577693832235 - b*s * 9.840557894587773 + a * 7.824159668166666 - a*s * 1.0878512413314014,
a^2 + b^2 - 1
```

However, the solution returned by msolve

`a, b, s, lamA, lamB = 0.8392867552141612, -0.5436890126920764, 1.8392867552141612, 1.8392867552141612, 1.8392867552141612`

is wrong. Interestingly, the solution is correct for the Gröbner basis system computed by msolve
```
lamA-1*lamB,
a-1*lamB+1,
lamB^2+b-1*lamB-1,
s*lamB+b-1*s-1,
b*lamB+s-1*lamB+1,
s^2+b-1*lamB-1,
b*s+1,
b^2-1*b-1*lamB+1
```

As of now, it seems that there are two possible problems. Either
1) The computation of the Gröbner system is wrong, resulting in a false solution. This is rather unlikely. 
2) The formatting of the input file is wrong. It seems like the parser is sensitive to some things a human might oversee. For example, the solver stops working it the equation system contains any leading plus sign (+) .

If the issue is the second problem: Could you please describe what the error is my problem formulation is? Perhaps it would be nice to have a small section in the readme where the required format is described in more detail. For example, it took a while until I figured out that the problem formulation should not include division (/). Thanks!

**Comment by mohabsafey** [comment]
Many thanks for using msolve. The issue in your input file format is that your coefficients are floating point numbers. You should coerce to exact rational numbers (e.g. 0.5 should be 1/2).  When doing so, it is in general worth to use dyaddic approximations (e.g. denominators are powers of 2).
Will add something about this in the README file, many thanks for the notice.

**Comment by ThomasSchnapka** [comment]
One more thing to add to the README that was not clear to me as a user: It seems like the constant term (exponent zero) cannot include an divisor.
