### ISSUE TITLE
Example takes way too long (again)

### ISSUE THREAD

**Issue by ederc** [algebraic-solving/msolve#156]
The example

x1,x2
0
x1+1267650600228229401496703205376,
x2+1267650600228229401496703205376

was fixed some time ago. Now it is again taking way too long and way too many primes. Before #153 this example took 0.01 sec, now about 10 sec. See also [corresponding Oscar test issue](https://github.com/oscar-system/Oscar.jl/issues/3956).

**Comment by mohabsafey** [comment]
This is fixed by PR #157

**Comment by ederc** [comment]
Thanks.
