### ISSUE TITLE
Support input files with dos line endings

### ISSUE THREAD

**Issue by vneiger** [algebraic-solving/msolve#182]
This is a suggestion to add support for input files that contain the dos "\r\n" line endings. An example received today was the attached file, run with ``msolve -f in.ms -o out.ms``.
[files.zip](https://github.com/user-attachments/files/17167288/files.zip)

**Comment by ederc** [comment]
msolve does not support Windows natively, Windows users need to use `wsl`. So why should we support dos file encodings?

**Comment by vneiger** [comment]
Editors may write in dos file format whatever the system. We had the case today, received by email, which is where the file in the above zip comes from (the person used ubuntu 22.04). I thought it was more efficient to add a test for '\r' in 3 or 4 lines of some msolve file rather than having to reply to such emails/issues every now and then; but feel free to ignore the PR if you prefer, this is not important.

**Comment by mohabsafey** [comment]
I do confirm we received such an email from a colleague using an old version of vim which was generating files with dos format for ending lines.
I did not check Vincent's PR yet but it we can handle this, it is good to take I think

**Comment by ederc** [comment]
This feature has been added via #183 and is included in v0.7.3 of msolve.
