### ISSUE TITLE
"segmentation fault" when attempting multithread calculation

### ISSUE THREAD

**Issue by jasonrong001** [algebraic-solving/msolve#26]
I am using MAC with M1 chip. 

Since apple's gcc seems to have issue with gmp, I was able to build with  

export LIBRARY_PATH=$LIBRARY_PATH:/opt/homebrew/lib

./autogen.sh

./configure CC=gcc-12 CFLAGS=-I/opt/homebrew/include

make

After that the single-thread calculation works fine, but the multithread calculation returns

zsh: segmentation fault  ./msolve -t 4 -f in.ms -o out.ms

**Comment by mohabsafey** [comment]
This bug is fixed in the new release 0.4.8
Many thanks for the feedback.
