### ISSUE TITLE
Oscar and msolve

### ISSUE THREAD

**Issue by iliailmer** [algebraic-solving/msolve#31]
Hi,

Is `msolve` still available via Oscar? I tried the latest version of 0.11.2 and `msolve` does not show as a command.

Thanks!

**Comment by ederc** [comment]
`msolve` functionality in OSCAR is right now available via `f4()`for Groebner basis computations and `real_solutions()` resp. `rational_solutions()`. Documentation for this will follow soon on the OSCAR side, see also `AlgebraicSolving.jl` for how to use these functions.
