### ISSUE TITLE
please upload a configured tarball to your release(s)

### ISSUE THREAD

**Issue by dimpase** [algebraic-solving/msolve#36]
Currently releases only package the version-controlled source files. However, the standard is to also provide tarballs with `./configure` etc present (these are automatically produced by `make dist`, to you just need to run this and upload the resulting tarball to release (click "edit release"). 

Now for SageMath we need to create such tarballs ourselves...

**Comment by ederc** [comment]
We updated the release.

**Comment by dimpase** [comment]
https://msolve.lip6.fr/downloads/v0.7.5/msolve-0.7.5.tar.gz does not have ./configure. This is a regression w.r.t. 0.6.5
(not sure where exactly this happened)
