### ISSUE TITLE
Building outside of source directory

### ISSUE THREAD

**Issue by mahrud** [algebraic-solving/msolve#43]
Compiling outside the source directory doesn't seem to work, probably due to something minor:
```
$ ls
AUTHORS  autogen.sh  configure.ac  COPYING  doc  INSTALL  interfaces  m4  Makefile.am  README.md  src  test
$ mkdir build
$ cd build/
$ ../autogen.sh 
autoreconf: export WARNINGS=
autoreconf: error: 'configure.ac' is required
```
You can still do `autoreconf -vif ..` or something like that, but that leaves some files in the source directory.

**Comment by mohabsafey** [comment]
This is now fixed. Many thanks.
