### ISSUE TITLE
Output file format for Groebner bases over the rationals

### ISSUE THREAD

**Issue by sumiya11** [algebraic-solving/msolve#86]
Hello,

I am using msolve to compute Groebner bases. 
For parsing the output basis, it can be useful for me if the formats of the output over a finite field and over the rationals would be similar. 

Currently, for the rationals, there seems to be no preamble:

```
$ msolve -g 2 -f input_qq -o output_qq
$ cat output_qq

[x+1
]:
```

but there is one for the finite fields

```
$ msolve -g 2 -f input_ff -o output_ff
$ cat output_ff

#Reduced Groebner basis for input in characteristic 11
#for variable order x, y, z
#w.r.t. grevlex monomial ordering
#consisting of 1 elements:
[1*x^1+1]:
```

The files `input_qq` and `input_ff` contain the following:
```
x, y, z
0
x + 1
```
and
```
x, y, z
11
x + 1
```

**Comment by ederc** [comment]
Fixed by #94
