### ISSUE TITLE
document meanings of columns in verbose output 

### ISSUE THREAD

**Issue by dimpase** [algebraic-solving/msolve#93]
currently with `-g 1/2 -v 2` one sees 
```
deg     sel   pairs        mat          density            new data         time(rd) in sec (real|cpu)
------------------------------------------------------------------------------------------------------
```
in the header, and while some of it can be guessed, some are totally cryptic.
This is how I think about it:

- deg : maximal degree of GB elements?
-  sel : ???
- pairs : number of unprocessed S-polynomials?
- mat/density : data for the current linear algebra solving stage?
- new data 
  * new : number of new GB elements?
  * zero: ???
- time(rd) in sec (real|cpu) : timing for the current stage

**Comment by ederc** [comment]
#94 adds an overview of the symbols stated.
